### ISSUE TITLE
Not rendering on 2019.2

### ISSUE THREAD

**Issue by WoLfulus** [gwaredd/UnityMarkdownViewer#1]
For some reason I couldn't make it work on 2019.2 - nothing gets rendered (default import). Plus some errors pop (about file location) if I try to move the the folder to a subdirectory.

Ideas?

**Comment by gwaredd** [comment]
It looks like Unity have changed how `TextAssets` work in 2019 - either intentionally or this is a bug.

For example, if I create an empty project and add a bunch of different text files (txt, json and md) then the default inspector also doesn't render anything either. I would have at least had a basic preview in 2018. Scripts appear ok but they are a different asset type IIRC.

The markdown viewer implements a `CustomEditor` for a `TextAsset`, which seems to be picked up correctly but doesn't call `OnInspectorGUI()` as expected. It's called on input events but not it appears on Layout and Render, suggesting a bug to me - or at least a half-baked behaviour change.

This might require some input from Unity and further investigation

**Comment by gwaredd** [comment]
Almost certainly this bug in 2019.2 ...

https://issuetracker.unity3d.com/issues/overridden-oninspectorgui-method-is-not-called-when-using-customeditor-typeof-defaultasset

Suggest you also login and upvote it, see if that gets unity's attention :)

https://forum.unity.com/threads/oninspectorgui-not-being-called-on-defaultasset-in-2019-2-0f1.724328/

**Comment by gwaredd** [comment]
Apparently there is a fix coming in 2020.1, however I've checked in a workaround for the bug in 2019.2.

https://github.com/gwaredd/UnityMarkdownViewer/commit/8e70f5b315a895799d03f268cf2fa9fd0d1131be
