### ISSUE TITLE
Usage within a IMGUI Container

### ISSUE THREAD

**Issue by trondtactile** [gwaredd/UnityMarkdownViewer#16]
Hello, big fan of this package!

I am trying to use your renderer inside a UIElements [IMGUI Container](https://docs.unity3d.com/ScriptReference/UIElements.IMGUIContainer.html), but it results in all text being rendered on the same line: 

![image](https://user-images.githubusercontent.com/38559434/112815584-c2012280-9080-11eb-83fd-c7c4932d4a64.png)

Any chance you could add support for this? :) 

Also, it would be super great if you could publish this repo as a NPM package to github. 

Doing so is really easy using Github Actions: https://github.com/marketplace/actions/npm-publish
You would need to add some lines to the `package.json` file:

```
"repository": {
    "type": "git",
    "url": "https://github.com/gwaredd/UnityMarkdownViewer.git"
},
"publishConfig": {
    "registry": "https://npm.pkg.github.com/@gwaredd"
}
```

By publishing it as a GitHub package, it becomes possible for other Unity packages to be set up to depend on this package, which would be very useful for us.

**Comment by gwaredd** [comment]
I have been busy with work so haven't had a chance to look at this. Do you have a project setup that demonstrates what you are trying to do that I can take a look? Thanks.

**Comment by trondtactile** [comment]
So the first issue was resolved by not creating a new renderer every frame. So never mind that one. But it would still be really great if you could publish this repo as a NPM package to Github :)
