### ISSUE TITLE
Unity Asset Store missing

### ISSUE THREAD

**Issue by jcs090218** [gwaredd/UnityMarkdownViewer#19]
Hi, thanks for the awesome tool! I think this tool was available on Unity Asset Store but I could not find it anymore? Am I missing anything? 😕

**Comment by gwaredd** [comment]
Hey, I am glad is has been useful for you :)

You are not missing anything, I am no longer supporting the Asset Store and have removed the project.

It should work with the unity package manager or [OpenUPM](https://openupm.com/) if you are looking for an alternative.

**Comment by jcs090218** [comment]
Got it! Thanks for your response! I will use OpenUPM instead! 💯 👍
