### ISSUE TITLE
Duplicating view

### ISSUE THREAD

**Issue by Biodam** [gwaredd/UnityMarkdownViewer#2]
Hello, I just found your asset and it seems pretty amazing.

But I'm having one problem:
![image](https://user-images.githubusercontent.com/15266822/68501135-2927f800-023c-11ea-8321-11ca5f3144b7.png)
The inspector view just duplicates.
I installed through the package manager (don't know if this makes any huge difference)

Thank you

**Comment by gwaredd** [comment]
Weird, which version of unity are you using?

**Comment by Biodam** [comment]
2018.4.0f1

Also I just tried to do a build and found the following errors:

`Library\PackageCache\com.mischief.markdownviewer@f9a6159493d69857b6fdfc8009b9ac476b5934a1\Runtime\MarkdownImporter.cs(4,32): error CS0234: The type or namespace name 'AssetImporters' does not exist in the namespace 'UnityEditor.Experimental' (are you missing an assembly reference?)`

![image](https://user-images.githubusercontent.com/15266822/68509818-a2c9e100-0250-11ea-84df-3aaad3021e50.png)

**Comment by gwaredd** [comment]
Oops, my bad. I put the wrong unity version in a recent fix :)

Try the latest  ...

https://github.com/gwaredd/UnityMarkdownViewer/commit/f1ae00653b8eec305f898a954256ffce919f09c5

This should fix the double rendering issue.

I'll look into the build error but you don't really need the asset importer in the run time. It's only for files with a `.markdown` extension anyway (not `.md`), for a quick work around you could just comment out this class

https://github.com/gwaredd/UnityMarkdownViewer/blob/master/Runtime/MarkdownImporter.cs

**Comment by Biodam** [comment]
Yeah, it fixed the double redraw.

I'm not yet familiarized with local editing packages, how a workaround like this would translate through git? Probably my teammates would need to redo the workaround right?

Still, I'll close this issue as the original problem was solved.

Thanks

**Comment by gwaredd** [comment]
Yeah, the unity packaged manger is pretty basic. I guess the easiest way to manage local changes would be to fork the project on github, make the change there and point to the fork instead. It would be a variation of the vendor drop model if you are familiar with that.

http://svnbook.red-bean.com/en/1.7/svn.advanced.vendorbr.html

**Comment by gwaredd** [comment]
I've moved the run time and made some minor fixes, let me know if you run into any issues

**Comment by Biodam** [comment]
Just tested, it seems to be building fine now, on Android both Mono and IL2CPP. Thank you.
