### ISSUE TITLE
Unnecessary debug logs in package

### ISSUE THREAD

**Issue by JKWax** [gwaredd/UnityMarkdownViewer#21]
`StyleConverter:37-39`
```
        public StyleConverter( GUISkin skin )
        {
            mReference  = new GUIStyle[ CustomStyles.Length ];
            mWorking    = new GUIStyle[ CustomStyles.Length ];

            for( var i = 0; i < CustomStyles.Length; i++ )
            {
                Debug.Log( mReference[ i ] );
                Debug.Log( skin );
                Debug.Log( CustomStyles[ i ] );

                mReference[ i ] = skin.GetStyle( CustomStyles[ i ] );
                mWorking[ i ]   = new GUIStyle( mReference[ i ] );
            }
        }
```    
![image](https://user-images.githubusercontent.com/86587893/124420449-93978f80-ddb3-11eb-84e7-25b33cab6cdf.png)

**Comment by gwaredd** [comment]
Not in the [latest code](https://github.com/gwaredd/UnityMarkdownViewer/blob/85e647015ed105970c1d3b62475d560de644cc81/Editor/Scripts/Layout/StyleConverter.cs#L37), where did you install it from?

**Comment by JKWax** [comment]
> Not in the [latest code](https://github.com/gwaredd/UnityMarkdownViewer/blob/85e647015ed105970c1d3b62475d560de644cc81/Editor/Scripts/Layout/StyleConverter.cs#L37), where did you install it from?

Ahh, major apologies... looks like one of our devs decided to modify the package and add those debug calls in.. we havent yet moved this package to the actual packages folder so its still included in our source control
