### ISSUE TITLE
Bug: no way to set base URL for images etc.

### ISSUE THREAD

**Issue by hybridherbst** [gwaredd/UnityMarkdownViewer#23]
When using UnityMarkdownViewer programmatically (e.g. downloading a .md file as text and then displaying it), images currently can't be properly resolved when the image URLs are relative to the markdown document location.

Would be great if there was a way to specify a base URL where relative URLs are then referred to (for example: a callback to decide for each URL what to do with it).

**Example:** download https://raw.githubusercontent.com/atteneder/glTFast/main/README.md via UnityWebRequest and display it by passing the text to a new MarkdownViewer.
**Expected:** can attach a callback for URls or specify the base URL in another way so that relative image URLs work
**Actual:** getting errors since the relative URLs can't be resolved properly

Right place for such a callback would probably be `MarkdownHandleImages.RemapURL`?

**Comment by gwaredd** [comment]
Yes, the best place would probably be to set the root URL as a property of the [HandlerImages](https://github.com/gwaredd/UnityMarkdownViewer/blob/ba4203635b555e30b76dd24438271843d5e78e83/Editor/Scripts/MarkdownViewer.cs#L35) object when the document is created and then update `RemapURL()` accordingly.

Note that URI's starting with `/` should be relative to the host as well where by default they are from the project directory.
