### ISSUE TITLE
Bold text looks bad

### ISSUE THREAD

**Issue by sindrijo** [gwaredd/UnityMarkdownViewer#28]
![image](https://user-images.githubusercontent.com/1384288/220364351-0f82d70d-7529-4a3e-943e-2e8799435474.png)

This is in `Unity 2021.3.x`.

The bolded text is implemented using Unity's boldening of a font referenced via GUIStyle but it seems it doesn't work so well with the included `SourceSansPro-Light` font.

I think a way to fix this would be to use the `SourceSansPro-SemiBold` or `SourceSansPro-Bold` to implement bolded text instead of relying on Unity's _boldening_ of an existing font. Probably this means doing the same for italic and italic+bolded.

This would probably require changes to the `StyleConverter` class, which currently looks like this:

```csharp
public GUIStyle Apply( Style src )
{
    if( src.Block )
    {
        return mWorking[ FixedBlock ];
    }

    var style = mWorking[ src.Size ];

    if( mCurrentStyle != src )
    {
      
        var reference = mReference[ src.Fixed ? FixedInline : Variable ];

        style.font             = reference.font; // Set different fonts based on normal/bold/italic/bold+italic
        style.fontStyle        = src.GetFontStyle(); // Always 'normal' instead of normal/bold/italic/bold+italic
        style.normal.textColor = src.Link ? linkColor : reference.normal.textColor;

        mCurrentStyle = src;
    }

    return style;
}
```

**Comment by gwaredd** [comment]
I'll take a look

**Comment by gwaredd** [comment]
Let me know if [e44f920](https://github.com/gwaredd/UnityMarkdownViewer/commit/e44f920220671a2c9cad3cac240a83f939c12087) this any better
