### ISSUE TITLE
How to change font?

### ISSUE THREAD

**Issue by IceCone-Topy** [gwaredd/UnityMarkdownViewer#29]
In a md file like this
```
### English 繁體中文

English 繁體中文

**English 繁體中文**

This is a sentence.

這是一個句子
```

And it is how it look like in unity inspector

![image](https://user-images.githubusercontent.com/79889802/223929611-c7a6f2c4-b3ec-4fd7-a53b-9dc9b41a71b7.png)

I think its bcuz the font dont support other language ?

so i want to change font that support more language for consistent looking in different language.

thanks for making this great plugin!!

**Comment by gwaredd** [comment]
Well the font supports simplified Chinese otherwise you would get no characters at all, although it needs some attention to how it handles emphasis see #28 

即使我只有基本的中文水平，我仍然能读懂它。 :)

Is there an alternative (open source, royalty free) font you have in mind? You should be able to change the font in the skin in the `Editor/Skin` folder.

**Comment by IceCone-Topy** [comment]
i will check #28 latter

i would like to use google noto sans font.
Just put font in that folder and rename to same name?

**Comment by sindrijo** [comment]
> i will check #28 latter
> 
> i would like to use google noto sans font. Just put font in that folder and rename to same name?

You can edit the GUIStyles that references the fonts, you'll want to switch out the fonts in the CustomStyles section of the GUISkin that are named `variable`, `fixed_inline` and `fixed_block`:

![image](https://user-images.githubusercontent.com/1384288/224322490-ba65ab8e-9799-4051-a5e2-c90929e5b1b8.png)

![image](https://user-images.githubusercontent.com/1384288/224322679-89b07208-54d7-4fa1-b103-44a35a531f3c.png)

**Comment by IceCone-Topy** [comment]
Thanks!!
After i search for better font. I found out [JetBrains Mono](https://www.jetbrains.com/lp/mono/).

So i change font to it.
And here's how it looks like

```
### English 繁體中文

English 繁體中文

**English 繁體中文**

**English** 繁體中文

This is a **sentence**.

這是一個**句子**
```

![image](https://user-images.githubusercontent.com/79889802/224597737-0f5f2756-1cfa-49c8-b615-1b67939c6f8c.png)

**Comment by gwaredd** [comment]
Changed font to JetBrains Mono, it does look much better :) 90bd7c8
