### ISSUE TITLE
MkViewer as component

### ISSUE THREAD

**Issue by MartinGonzalez** [gwaredd/UnityMarkdownViewer#3]
Hi!
Is there a chance to have the MdViewer like a component to use it in a EditorWindow?
I have the .md string and it would be cool to have something like

MarkdownViewer.For(myMdAsString).Render();

**Comment by gwaredd** [comment]
It would be cool :) and theoretically reasonably straightforward (with a bit of monkeying around with the unity editor layout).

Not something I will have time to look at anytime soon but if you had a pull request I could look to merge it in.

**Comment by MartinGonzalez** [comment]
Nice, I will take a look to create a PR!
