### ISSUE TITLE
Render markdown in custom editor window script?

### ISSUE THREAD

**Issue by ntt-ebehar** [gwaredd/UnityMarkdownViewer#34]
Is it possible to render a markdown file using this package in a custom script? I'm hoping I can hook this up to my custom editor window so I can avoid writing a translation layer so my markdown files will render properly according to the markdown syntax/style.

**Comment by gwaredd** [comment]
Potentially :) The [MarkdownViewer](https://github.com/gwaredd/UnityMarkdownViewer/blob/main/Editor/Scripts/MarkdownViewer.cs) class is the entry point for the rendering, it just has `Draw()` and `Update()` functions. However, it makes some assumptions around width and height of the target that might not hold up if you are trying to use this inside a custom editor. So you might need to adapt it slightly. See also [MarkdownEditor](https://github.com/gwaredd/UnityMarkdownViewer/blob/main/Editor/Scripts/MarkdownEditor.cs) for how it is used.

GL & HF
