### ISSUE TITLE
How is SkinLight and SkinDark Assigned?

### ISSUE THREAD

**Issue by Kaveinator** [gwaredd/UnityMarkdownViewer#36]
I tried creating a `MonoBehaviour` component to try and add markdown enabled notes to be rendered, which basically needsneeds a reference to ~~MarkdownAsset~~, wait nevermind a _FileAsset_.

Now, I have been trying to see _how_ SkinLight and SkinDark variables in the Editor were assigned. Its been 3 hours, still no clue. At this point, I am questioning my sanity..... I wasn't able to find a call to a "Resources" class _(for `Resources.Load`)_ and "AssetDatabase" _(for presumably `AssetDatabase.LoadAssetAtPath`)_. I cannot tell what is assigning these variables:

https://github.com/gwaredd/UnityMarkdownViewer/blob/2cbf0b999a76526ddc3f1fc77b11b04d69039c30/Editor/Scripts/MarkdownEditor.cs#L12-L13

And the only reference I found for it is:
https://github.com/gwaredd/UnityMarkdownViewer/blob/2cbf0b999a76526ddc3f1fc77b11b04d69039c30/Editor/Scripts/MarkdownEditor.cs#L28

MarkdownViewer doesn't care if you pass a null skin, it will just error out once it uses it. 

Anyone knows how it works?

**Comment by gwaredd** [comment]
This might help ...

Skins are just assets (e.g. `Editor/Skin/MarkdownSkinDark`)

The references to them are held with the MarkdownEditor script (click on the script and you can see you can change these in the inspector).

Unity fills the reference when it creates the object just as it would any game object in the scene graph. So MDV does not need to load them directly. The confusion is I think that this is an editor script and not a typical game component that you might be used to, same process though.

HTH

**Comment by Kaveinator** [comment]
I completely forgot that you were able to set defaults on scripts, this makes a ton of sense now. Gonna see if I can finish the markdown components, having other issues with how markdown is rendered (it clears anything field I add _(understandably so)_. Worst case scenerio, you'd have to set the file reference via Debug mode in Inspector.
