### ISSUE TITLE
Update on Unity Asset Store

### ISSUE THREAD

**Issue by tacman** [gwaredd/UnityMarkdownViewer#7]
Love this, but the version in the asset store doesn't work with Unity 2020, can you update it please to the latest/greatest?

Also, the link in the asset store isn't right.

https://assetstore.unity.com/packages/tools/utilities/markdown-viewer-138882

![image](https://user-images.githubusercontent.com/619585/97109063-90d28f80-16a7-11eb-945b-8b8d8c2b064a.png)

(Goes to unium).

**Comment by gwaredd** [comment]
Ah yes, the asset store is always an after thought. I'll update it when I get a moment. Thanks for the catch

**Comment by tacman** [comment]
Thanks.  I'm standardizing some demo projects, and would like to make this
part of my normal setup.

**Comment by gwaredd** [comment]
I've updated the asset store. The package needs to be reviewed by unity so may show up in a few days.

Just FYI, I am considering removing the package from the asset store in the future so github will be the only way to access the code.

**Comment by tacman** [comment]
Yeah, I've wondering if that would be a better approach for free packages,
but I don't know how caching package works.  Ideally if you add a package
via github, it would first check the local downloads and not refetch it.
Ideally, it wouldn't even try if the version matched.  That'd be very
helpful for those of us on slow or unreliable internet connections.
