### ISSUE TITLE
Render Markdown in TextMeshPro

### ISSUE THREAD

**Issue by tacman** [gwaredd/UnityMarkdownViewer#8]
Is there a way to render Markdown in a TextMeshPro component?

I'm thinking Markdown -> HTML, but maybe Markdown to something that Unity supports directly?

No answers to this question, which is the same thing: https://forum.unity.com/threads/simple-html-markdown-renderer-for-textmeshpro.838876/

Any thoughts on how to approach this?  Would love to leverage this component into the Unity runtime.

**Comment by gwaredd** [comment]
That depends on what you are trying to achieve.

UMV uses [markdig](https://github.com/lunet-io/markdig) to parse the Markdown. It would be relatively easy to do the same thing but output the rich text tags that TMP supports instead.

However, TMP does not support tables, horizontal lines, block quotes, images or bulleted lists. Nor does it support any interactive content such as links or page navigation. So using rich text tags would only be a light version of markdown.

To get a full featured version you would need to take control over the layout. This is what UMV does, it uses the GUI to render each component (word by word) but handles the layout itself (as the Unity GUI doesn't support what is required). A similar approach might work with TMP whereby each word would be its own component and the layout / positioning handled by the parent. Might be a bit slow though.

The more elegant approach would be to write a new component that is an amalgamation of the UMV layout code with the font rendering capabilities of TMP.

**Comment by tacman** [comment]
Using the font support from https://docs.unity3d.com/Packages/com.unity.ugui@1.0/manual/StyledText.html would be a pretty great start, but that would only be for a single block of text. 

I'm guessing that providing support for paragraphs, hr, and headers wouldn't be too hard, since they'd become children of the layout.

My idea is to be able to easily incorporate some text written in markdown into the application -- help, about, history, credits, etc.  

I looked at this tool, and tweaked the code enough that it would compile.  The basic HTML rendering appears to work okay.

https://assetstore.unity.com/packages/tools/gui/powerui-html-css-10374

So maybe it'd make more sense to integrate MarkDig in this package to convert from markdown to HTML?  Or tweak UMV to render a subset of HTML on an object with TMP children?

**Comment by gwaredd** [comment]
If you had a package like PowerUI that supported enough HTML for what you want then converting markdown into HTML or html-like tags with markdig is very easy - in fact it even has a `ToHTML()` function if I recall. So I would do that :)

If you wanted to use TMP for all the funky text effects (like, shadow, gradients, etc), I would use markdig to output the rich text tags TMP supports - possibly creating a new component for paragraphs and whatnot. You can checkout the [UMV "renderer"](https://github.com/gwaredd/UnityMarkdownViewer/tree/master/Editor/Scripts/Renderer) and the [ParseDocument()](https://github.com/gwaredd/UnityMarkdownViewer/blob/f0982054d638e4365569dffbbdce4a3d33bf7891/Editor/Scripts/MarkdownViewer.cs#L50) function which shows how to hook into the markdig callbacks.

In both cases, if the data was static you could even do this in a build step or some kind of pre-process to save the runtime overhead if you care about that kind of thing.

If you wanted to do something more bespoke then you need to take over the layout of the text and images yourself. This is much more work but gives you more control. The complexity for UMV came with handling images inlined into the text (which are asynchronously loaded in the background) and having to manually take care of the word wrapping that came with it.

UMV is tied into the Unity editor, along with all the nonsense and quirks that come with it. It might be a reasonable starting point for something custom but I doubt it's something you'll be make a few tweaks and expect it to work. You would probably have to gut it, unhook the editor stuff and recombine it into a component.

HTH, G

**Comment by tacman** [comment]
The new Unity UI is is going to use an XML-based layout system, and while it's not HTML, I think it makes more sense to use that tool or some other tool, rather than trying to render markdown->HTML->TextMeshPro, so I'll close this issue.  Thanks for the discussion though!
