### ISSUE TITLE
UnityWebRequest.isHttpError' is obsolete: 

### ISSUE THREAD

**Issue by tacman** [gwaredd/UnityMarkdownViewer#9]
I noticed these messages when upgrading to 2020

Assets/UnityMarkdownViewer/Editor/Scripts/MarkdownHandleImages.cs(159,17): warning CS0618: 'UnityWebRequest.isHttpError' is obsolete: 'UnityWebRequest.isHttpError is deprecated. Use (UnityWebRequest.result == UnityWebRequest.Result.ProtocolError) instead.'

I also get this, but I don't know if it's related to UMV:

Failed to destroy editor windows: #1
FallbackEditorWindow
UnityEditor.WindowLayout:LoadDefaultWindowPreferences () (at /home/bokken/buildslave/unity/build/Editor/Mono/GUI/WindowLayout.cs:72)

**Comment by gwaredd** [comment]
I'm not seeing this in the latest (`2020.1.11`) and isHttpError is not flagged as deprecated. What's the exact engine version?
